# This file should contain all the record creation needed to seed the database with its default values.
# The data can then be loaded with the rake db:seed (or created alongside the db with db:setup).
#
# Examples:
#
#   cities = City.create([{ name: 'Chicago' }, { name: 'Copenhagen' }])
#   Mayor.create(name: 'Emanuel', city: cities.first)


products = [
	['Alitura Clay Mask', '748252963116'],
	['Alpha BRAIN - 30 ct. Veggie Capsules', '819444010007'],
	['Alpha BRAIN - 90 ct. Veggie Capsules', '819444010182'],
	['Brain Octane Oil - 3 Oz.', ''],
	['Bulletproof Brain Kit', ''],
	['Bulletproof Coffee Kit', ''],
	['Bulletproof Coffee Kit - Decaf', ''],
	['Bulletproof T-Shirt - "Bulletproof Babe" - Womens L', 'TS-BABE-W-L'],
	['Bulletproof T-Shirt - "Bulletproof Babe" - Womens M', 'TS-BABE-W-M'],
	['Bulletproof T-Shirt - "Bulletproof Babe" - Womens S', 'TS-BABE-W-S'],
	['Bulletproof T-Shirt - "Bulletproof Babe" Womens XL', 'TS-BABE-W-XL'],
	['Bulletproof T-Shirt - "Caffeine Is My Drug" - Mens 2XL', 'TS-CAF-M-2XL'],
	['Bulletproof T-Shirt - "Caffeine Is My Drug" - Mens L', 'TS-CAF-M-L'],
	['Bulletproof T-Shirt - "Caffeine Is My Drug" - Mens M', 'TS-CAF-M-M'],
	['Bulletproof T-Shirt - "Caffeine Is My Drug" - Mens S', 'TS-CAF-M-S'],
	['Bulletproof T-Shirt - "Caffeine Is My Drug" - Mens XL', 'TS-CAF-M-XL'],
	['Bulletproof T-Shirt - "Caffeine Is My Drug" - Womens L', 'TS-CAF-W-L'],
	['Bulletproof T-Shirt - "Caffeine Is My Drug" - Womens M', 'TS-CAF-W-M'],
	['Bulletproof T-Shirt - "Caffeine Is My Drug" - Womens S', 'TS-CAF-W-S'],
	['Bulletproof T-Shirt - "Caffeine Is My Drug" - Womens XL', 'TS-CAF-W-XL'],
	['Bulletproof T-Shirt - Gray - Womens', 'TS-GRAY-W-S'],
	['Bulletproof T-Shirt - Gray - Womens', 'TS-GRAY-W-XL'],
	['Bulletproof T-Shirt - Gray - Womens', 'TS-GRAY-W-L'],
	['Bulletproof T-Shirt - Gray - Womens', 'TS-GRAY-W-XS'],
	['Bulletproof T-Shirt - Gray - Womens', 'TS-GRAY-W-M'],
	['Bulletproof Total Upgrade Kit', ''],
	['Bulletproof Upgraded Coffee - 3oz', ''],
	['Bulletproof Upgraded Decaf Ground Coffee - 12oz.', ''],
	['Bulletproof Whey Smoothie Kit', ''],
	['Bulletproof AirScape Kitchen Canister', '654771002015'],
	['Bulletproof AirScape Kitchen Canister - (NEW BRANDING)', '654771002015'],
	['Bulletproof Cacao Tea', '748252962515'],
	['Bulletproof Coffee Starter Kit - Brain Octane Edition', ''],
	['Bulletproof Diet Roadmap Poster', '748252962911'],
	['Bulletproof GABAwave', 'BulletproofÂ® GABAwave'],
	['Bulletproof Ground Coffee 12oz', ''],
	['Bulletproof Sleep Induction Mat', ''],
	['Bulletproof Travel Mug', 'WLH100E01'],
	['Bulletproof Truffled Chocolate Coffee Beans', '696859061912'],
	['Bulletproof Upgraded Aging Formula', '713757860512'],
	['Bulletproof Upgraded Brain Octane Oil - 16 oz.', '696859061905'],
	['Bulletproof Upgraded Brain Octane Oil - 32 oz.', '696859061868'],
	['Bulletproof Upgraded Cacao Butter', '713757860017'],
	['Bulletproof Upgraded Chocolate Powder', '713757860116'],
	['Bulletproof Upgraded Coconut Charcoal', '696859061882'],
	['Bulletproof Upgraded Coffee - 12 oz.', '794504284027'],
	['Bulletproof Upgraded Coffee - 5 lb.', '713757015431'],
	['Bulletproof Upgraded Coffee Cartridges', '696859061875'],
	['Bulletproof Upgraded Coffee Decaf - 12 oz.', '696859061844'],
	['Bulletproof Upgraded Coffee Decaf - 5 lb.', '696859061851'],
	['Bulletproof Upgraded Collagen Protein', '713757860215'],
	['Bulletproof Upgraded Glutathione Force', '713757874328'],
	['Bulletproof Upgraded MCT Oil - 16 oz.', '696859061837'],
	['Bulletproof Upgraded MCT Oil - 32 oz.', '713757860314'],
	['Bulletproof Upgraded Vanilla', '713757860413'],
	['Bulletproof Upgraded Whey 2.0', '794504890013'],
	['California King - Dual Temperature Zone', '1099'],
	['Choline Force', '748252963611'],
	['CILTEP Nootropic Stack 60 ct.', '79829545252'],
	['Coffee Kit - Brain Octane Edition', ''],
	['Coffee Kit - Decaf & Regular', ''],
	['DS:  Bulletproof Vibe Whole Body Vibration Plate', 'BVWBVPLATE'],
	['DS:  Focus Brain Trainer', 'NIRHEG'],
	['DS:  Greenwave EMF Filters - Starter Kit (4)', 'GWEMFFILTERS-4'],
	['DS:  Greenwave EMF Filters - Travel Kit (2)', 'GWEMFFILTERS-2'],
	['DS:  HeartMath EmWave2', 'HMEW2-CG'],
	['DS:  HeartMath EmWave2', 'HMEW2-SB'],
	['DS:  HeartMath Inner Balance Sensor for iOS', 'INNERBALANCE'],
	['DS:  HeartMath Inner Balance Sensor for iOS - Lightning', 'INNERBALANCE Lightning'],
	['DS:  NeurOptimalÂ Personal Trainer Bundle', 'NEUROPTIMALPT'],
	['DS:  Zona Plus Version 3', 'ZONAPLUS3'],
	['Full - Single Zone', '$649'],
	['HeartMath EmWave2 - Charcoal Gray', 'HMEW2-CG'],
	['Java Jackets', 'Java Jackets'],
	['King - Dual Temperature Zone', '$1,099'],
	['Low-Blue Nightlight', 'NIGHTLIGHT'],
	['MCT Oil - 3 Oz.', ''],
	['Mens Bulletproof T-Shirt', 'TS-GRAY-M-S'],
	['Mens Bulletproof T-Shirt', 'TS-GRAY-M-M'],
	['Mens Bulletproof T-Shirt', 'TS-GRAY-M-L'],
	['Mens Bulletproof T-Shirt', 'TS-GRAY-M-2XL'],
	['Mens Bulletproof T-Shirt', 'TS-GRAY-M-XL'],
	['MitoQ Moisturizing Anti-Aging Serum 50ML', ''],
	['PowerLung Washe - 6 oz.', '679873900061'],
	['Powerlung Respiratory & Lung Strength Trainer', ''],
	['Queen - Dual Temperature Zone', ''],
	['Single (Split Queen 30" x 75")', ''],
	['Split Cali King (36" x 84")', ''],
	['The Better Baby Book', '9781118137130'],
	['Twin XL (Split King 38" x 80")', ''],
	['Unfair Advantage', ''],
	['UP:  Bulletproof Sticker Insert', 'BPESTICKERS'],
	['UP:  Consumer Brochures', ''],
	['UP:  Crossfit Brochure', 'Crossfit Brochures'],
	['UP:  Kit Band - Everyday Band', 'Everyday Kit Band'],
	['UP:  Kit Box - 9x9x5', 'KG12'],
	['UP:  Mens Journal Reprint', ''],
	['UP:  Recipe Card', ''],
	['UP:  Recipe Card - with 15% discount', ''],
	['Upgradedself.com $25 Gift Card', ''],
	['Upgradedself.com $50 Gift Card', ''],
	['Upgraded Brain Octane Oil - 3 Pack', ''],
	['Upgraded Brain Octane Oil - 32oz', ''],
	['Upgraded MCT Oil - 3 Pack', ''],
	['Alitura Clay Mask - Labels', 'Alitura Clay Mask - Labels'],
	['Alitura Clay Mask - Seals', 'Alitura Clay Mask - Seals'],
	['Brand Transition Sticker', ''],
	['BulletProof New Energy Kit', ''],
	['Bulletproof Travel Mug - (New Branding)', ''],
	['Bulletproof Ghee', '748252962614'],
	['Bulletproof Intro Kit (Amazon Exclusive) 12oz ground coffee, 16oz Brain Octane', ''],
	['Bulletproof Sleep Induction Mat - Label', ''],
	['Bulletproof Sleep Induction Mat - Misc Parts', ''],
	['Bulletproof Sleep Induction Mat - Tube (5" DIA x 21" L)', ''],
	['Chocolate Bar', ''],
	['Kit Band - Mind Upgrade Band', ''],
	['Limited Edition Coffee Connoisseur Kit', ''],
	['Mind Upgrade', ''],
	['Powerlung Respiratory & Lung Strength Trainer', '679873002000'],
	['PowerLung Washe - 6 fl. oz.', ''],
	['UP:  Bulletproof Patches - Gray/Black', 'PATCHES-GR-BLK'],
	['UP:  Diet Roadmap Stickers', 'Diet Roadmap Stickers'],
	['UP:  Prop 65 Sticker', 'PROP65STICKERS'],
	['UP:  Recipe Card - Crossfit Games', ''],
	['UP:  Recipe Card - Scorcher', ''],
	['UpgradedSelf.com Gift Card', 'GIFTCARD']
]
products.each do |product|
	Product.create(name: product[0], sku: product[1])
end


